### ISSUE TITLE
Force SSL connection

### ISSUE THREAD

**Issue by ChrisASearles** [ChrisASearles/CompLinks#40] opened 2017-05-08 13:35 UTC
URL rewrite to always force HTTPS connections.

**Comment by cgladue** [comment] 2017-05-13 18:43
done, HTTP is redirect 301 to https

**Comment by ChrisASearles** [comment] 2017-05-15 15:46
I'm not being redirected on the shop.complinks.co sub

**Comment by cgladue** [comment] 2017-05-15 15:47
yea it was done, but ron needs to install the certificate on his other server hosted at godaddy before i turn it back on otherwise it takes that server offline by requiring the SSL through cloudflare since both servers are behind the same domain on cloudflare.

**Comment by robgpeak** [comment] 2017-05-15 16:42
I just got off the phone with Godaddy support about the SLL and he said it is seemingly installed properly on the www.complinks.co site which is doing an automatic redirect to https, but it is actually going to complinks.co instead of www.complinks.co.  This must because the "script" or plugin is making that happen, but to be honest, I have no idea why, or how to fix it.

I am using the really-simple-ssl/rlrsssl-really-simple-ssl.php plugin, but when I look at it, I really don't know what I am looking at.  It's all greek to me.

When I explained to the guy on the phone about the set up we have with hosting at two separate locations, he said something about the "scripting" (he may not have used that exact term) in the 301 on AWS needs to be written to exclude "www" as a subdomain in the wild card SSL.  That is most likely to be what's causing the undesired effect when you force the 301 on the subdomain SSL, and it is messing up the SSL on the www site.

**Comment by cgladue** [comment] 2017-05-15 16:45
are you able to give me access to the control panel for the godaddy hosting ?

the problem is cloudflare, there is 1 domain which covers complinks.co (and all subdomains, including www. and shop. and all others,

id like to take a look at the hosting setup for complinks.co if possible

**Comment by robgpeak** [comment] 2017-05-16 18:24
@cgladue The forced SSL on the subdomains is not working again.  Please look at it and tell me if there is anything else I can do with godaddy?  The one at www is still working fine...

**Comment by cgladue** [comment] 2017-05-16 18:28
@robgpeak it was my bad, i had changed it on the server when i was testing and never put it in the Project so when i re-deployed to add the activity stream archiving it overwrote it, but its back now.

on a side note, you can archive the activity stream now, just select the row by clicking on it, you can shift click to select multiple or ctrl click like usual to select 1 row at a time.

**Comment by robgpeak** [comment] 2017-05-16 18:35
cool on the SSL.  As for the Activity Stream update, I am going to close this issue and make a comment in #88

**Closed by robgpeak** 2017-05-16 18:35 UTC
Labels: 4 - Review
