### ISSUE TITLE
Names for the "Container" sections on the front end

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#59] opened 2017-05-08 22:56 UTC
@ChrisASearles I just did a search here on Huboards for the word "Disclaimer" as it appeared in #33 but I was confused as to how it would have gotten that name.  In the mockup https://app.moqups.com/robg/QSDVx2F07W/edit/page/ab309be6f it was call Conditions, and in fact I just tweaked in on that moqups page to more closely resemble the layout that Derek has put in place.  And I included a comment next to it that includes the icon to use. https://material.io/icons/#ic_border_color

While we're there, on the live site of the "Store Index" page, the container at the bottm left reads, "Rewards" but as per the moqups it should read "Deals and Promotions"

**Comment by ChrisASearles** [comment] 2017-05-10 13:46
This is a duplicate of #29

**Closed by ChrisASearles** 2017-05-10 13:46 UTC
Labels: 0 - Backlog
