### ISSUE TITLE
Adjusting the location of the dropdown menu under authenticated user

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#115] opened 2017-05-18 21:53 UTC
As it appears now, the menu covers the user's name and points, and I think it would look better if it appeared below that so the user's name and points were still visible.

This was sort of associated with issue #42, but I thought it might need it's own issue, not sure.

**Comment by ChrisASearles** [comment] 2017-05-22 23:12
@robgpeak This was done by design and is a default material style, primarily for usability on mobile devices (small screens with limited real estate and the user's finger is already hovering over an option rather than definitely needing to move) but we can change it if you'd prefer it to load below. Please just confirm before I assign it.

**Comment by robgpeak** [comment] 2017-05-22 23:17
I think there is plenty of room below the still leave the user's name and points visible...
![screenshot_2017-05-22-19-15-02](https://cloud.githubusercontent.com/assets/28393235/26332215/413b3d00-3f23-11e7-96ea-722f25a1599c.png)

**Comment by ChrisASearles** [comment] 2017-05-22 23:23
@robgpeak actually, the name and point total showing on mobile currently is a bug. @Dwells7583 any word on why that is loading like that (it might have been something I did at one point). There will definitely not be enough room for the search button, logo, menu button, and the length of a user's name we potentially need to fit at mobile. I believe I added that info to the side menu on mobile to avoid this problem.

**Comment by robgpeak** [comment] 2017-05-22 23:38
Just for shits and giggles, sign up for an ebates account, and see how they do it.  That might be a good alternative.

**Comment by ChrisASearles** [comment] 2017-05-22 23:48
Can you send a screen cap?

**Comment by robgpeak** [comment] 2017-05-23 00:19
Here is is.  They actually take the My Account links and all the other menu items that normally show up in right hand side menu, and move them to the hamburger menu...
![screenshot_2017-05-22-20-16-33](https://cloud.githubusercontent.com/assets/28393235/26333464/e7b9a22c-3f2b-11e7-8b8b-7fb28dbd1f2e.png)

**Comment by ChrisASearles** [comment] 2017-05-23 00:54
Ok, that's basically what I was proposing. We can fit the my account without a problem if we do it the way I proposed initially (we don't have to mimic EVERYTHING Ebates does ;-) ).

**Comment by robgpeak** [comment] 2017-05-23 00:56
My only objection and comment on that layout was that the drop-down menu covered up the username and I didn't think that was appropriate. I am dictating this into my phone so take it for what it's worth if there's typos and it might not make sense. Still Furniture shopping

**Comment by ChrisASearles** [comment] 2017-05-23 01:30
@Dwells7583 i moved the menu and hid the name and point balance on mobile but I'm having an issue with the button locations on mobile that you need to take a look at.

**Comment by ChrisASearles** [comment] 2017-05-23 01:36
@Dwells7583 I'm going to push this through to review and open my last comment as a new issue.

**Comment by cgladue** [comment] 2017-05-23 01:39
published

**Closed** 2017-06-02 17:59 UTC
Labels: 4 - Review
