### ISSUE TITLE
Browser Header Color

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#126] opened 2017-05-20 18:14 UTC
If you look at the header in the mobile responsive version if the website, you'll see the hamburger menu gets covered by the logo, and the logged in area in the top right cuts off the users name.

I put together a crude mock up of a possible layout that would work... https://app.moqups.com/robg/QSDVx2F07W/view/page/ae08cbf01

Here is a screenshot of the current header...
![uploads/7e8e162e-47ba-43d5-b91b-876f73ca007a/Screenshot_2017-05-20-14-04-09.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7e8e162e-47ba-43d5-b91b-876f73ca007a%2FScreenshot_2017-05-20-14-04-09.png)

While you're in there, this might be a separate issue, but I would like the overall browser window instead of turning light blue, it should remain the default color of the person's normal browser color.

**Comment by ChrisASearles** [comment] 2017-05-23 20:18
Most of this is a duplicate of #128 so I'm changing to just refer to the theme color we're changing. This color will change based on the theme color for the casino. We thought it was a nice design touch to make the site feel more like a native app, any particular reason you want it set back to the default color @robgpeak ?

**Comment by robgpeak** [comment] 2017-05-23 21:24
Ok you can leave as the color you have it. And let it match the theme

**Closed** 2017-05-31 13:50 UTC
Labels: 0 - Backlog, wontfix
