### ISSUE TITLE
Limit Search Results

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#190] opened 2017-06-07 12:56 UTC
@cgladue I get the following server application error when I do a search for one letter, and sometimes with two letters in the search.

I know we put the autocomplete search functionality on the shelf for now, but I NEVER like seeing a page like this...  Can we simply return all stores that start with that letter for now, AND disable showing any results in the "You Might Also Like" section, JUST for a search result from one or two letters?

![uploads/a27260ee-ed36-44eb-8860-2959d88f9a2e/Screen Shot 2017-06-07 at 8.49.11 AM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2Fa27260ee-ed36-44eb-8860-2959d88f9a2e%2FScreen+Shot+2017-06-07+at+8.49.11+AM.png)
or

**Comment by ChrisASearles** [comment] 2017-06-08 19:22
@cgladue looks like an issue with returning too many results from the DB. I would think we could get away with a TOP(50) or so, what do you think?

**Comment by cgladue** [comment] 2017-06-08 20:02
@ChrisASearles should work, ill do this tonight

**Comment by cgladue** [comment] 2017-06-08 20:02
ill return the top 50 based on total views.

**Comment by cgladue** [comment] 2017-06-08 23:59
@robgpeak @ChrisASearles Search results have been limited to top 50 results based on # of views as well as top 50 Similar stores

**Comment by robgpeak** [comment] 2017-06-09 00:08
I just cleared my cache and tried it again (searching for the letter "a") and I got the same error message as originally posted.

**Comment by cgladue** [comment] 2017-06-09 00:15
the problem isnt related to the # of results, its actually that there is some advertiser in there that has no category assigned but yet is still marked as active.  so i put in a check to make sure the advertiser is in at least 1 category.

**Comment by cgladue** [comment] 2017-06-09 00:15
try it again

**Comment by robgpeak** [comment] 2017-06-09 01:19
Are Similar stores the same as You Might Also Like stores?  The reason I ask is I read above that you were going to limit the number of Similar stores to 50, and since it was in this same issue thread, I figured that to mean it had something to do with the Similar stores to the search results, but the section is actually called You Might Also Like stores, and they currently yield more than 50 stores when you search the letter a for example.  (If you do a search for a single letter you'll see what I mean.

Otherwise, all the stores that start with the letter a appear with a search for "a", and that is fine.

**Comment by cgladue** [comment] 2017-06-09 01:22
Actually i should of said 2 similar stores per search result, so if you search for something that yields the max of 50 results there could be 100 similar stores .. but most of the time there will be fewer results and at most 2 * # results similar stores...

and yes "you might also like" is similar stores, a.k.a stores from the same categories as the results..

**Comment by ChrisASearles** [comment] 2017-06-22 01:31
@robgpeak what's the status on this?

**Comment by robgpeak** [comment] 2017-06-22 13:05
The problem is, the similar stores are being replicated...

Please do two separate searches, one for "pet" and the other for "shoe" and you'll see what I mean.  

I am not sure I know the right fix at the moment, but the first thing that pops in my mind which might be a simple fix is, if the store is in the search results, don't show it in similar stores, and if it already in similar stores, don't show it again.

**Comment by cgladue** [comment] 2017-07-09 02:47
@robgpeak i have stopped the duplicate similar search results from appearing.

**Closed** 2017-07-09 12:15 UTC
Labels: 4 - Review
