### ISSUE TITLE
Email and password only two fields needed for sign up

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#63] opened 2017-05-09 00:55 UTC
Please follow the notes on https://app.moqups.com/robg/QSDVx2F07W/edit/page/a93e4a7ba as it clearly articulates my reasoning for just capturing email and password on Sign Up. (no first and last name). It may spur other discussions, but we should have them in moqups or verbally.

**Comment by ChrisASearles** [comment] 2017-05-10 14:15
Closing this as a duplicate of #69

**Closed by ChrisASearles** 2017-05-10 14:15 UTC
Labels: 0 - Backlog
