### ISSUE TITLE
Keeping the verbiage, letter capitalization and different font sizes consistent

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#125] opened 2017-05-19 22:06 UTC
It looks like in some of the containers it says, "Earn x points/$" or "Earn up to x points/$", which is fine when the only difference is the 'up to', but then there are other containers that read "x points/$".  Actually, now that I am looking at it, it seams like it is only the featured stores containers that are showing the "Earn" in them, and that is probably OK.

I think users will see that on the home page, above the fold, and get it, then we probably don't need to show it in the Store Boxes themselves...

Next, I notice some read, "See all <store name> deals" (currently in the Shop Featured Books & Digital Media Deals as an example), some say "Shop all <store name> deals" (in the Store Boxes and the Featured Stores on the home page), and some say, "View all <store name> deals" (in the Shop Featured Deals section on the home page).  For continuity and consistency, let's use, "See all <store name> deals" universally.

As for the font sizes, again, I think it make sense to keep consistency throughout the site.  All the "See all <store name> deals" should be the same size font as the other ones in the all the containers. All the "x points/$" should be consistent with each other in other containers.  I like the bold font there.

All the "Show Now" buttons including the little arrow pointing right, should be the same wherever they appear on the site.

**Comment by ChrisASearles** [comment] 2017-05-23 20:09
@robgpeak 

(*Note that the following does not apply to the store detail page and one or two other sections of other pages we're actively working on that are already being tracked as issues.)

We standardized a set of these that are all pulling the same regardless of what page the item lives on. If there is any inconsistency between sections at this point (i.e. featured deals vs featured advertisers) it's likely by design. In those cases, if there is specific wording you'd prefer over what's being used, or if you don't like some part of the design, please add each one as an individual issue with the device and browser you're using so we can reproduce the problem and fix accordingly.

For now I'm going to mark this particular issue as closed as the framework for ensuring as much consistency as we can ensure (barring user error) has been put in place.

**Closed by ChrisASearles** 2017-05-23 20:09 UTC
Labels: 3 - Working <= 3

**Comment by robgpeak** [comment] 2017-05-24 12:40
Chris, this may come across as rude an obnoxious, and I apologize in advance, but no.  I am NOT going to create a new issue for each instance where the words are not consistent.  I know sometimes texting, email, and this type of communication here in github, sometimes things get confused in the communication, and we might not be speaking about the same thing...

You wrote, "...We standardized a set of these that are all pulling the same regardless of what page the item lives on..."  When I read that, to me it sounds like, "There is a field in the db with a name something like 'sub-text' that would be referenced from all the different types of containers.  Store Boxes, Featured Advertisers, etc.  The entry in that field is 'See all <Store_Name> deals', so anywhere that shows up on the site, the text that is visible to the end user on the front end would be exactly that.

IF you have different fields in the db for different containers, meaning you have a 'sub-text' data field in the Store Box container, and a 'sub-text' field in the Featured Advertiser container, and another 'sub-text' field in a different container, that's fine, just please make them ALL read, 'See all <Store_Name> deals'

As a bit of further explanation of my reasoning of the specific wording and the consistency.  The part of the overall container in which this copy resides, when clicked will take the user to the store index page where he can SEE the deals.  When he clicks any of the SHOP NOW buttons, he will be taken on a shopping trip to that store.
