### ISSUE TITLE
Layout for Store Index Pages

### ISSUE THREAD

**Issue by robgpeak** [ChrisASearles/CompLinks#66] opened 2017-05-09 18:53 UTC
For the sake of brevity and clarity, I would like the site to look like this https://app.moqups.com/robg/QSDVx2F07W/edit/page/ab309be6f

I know there are a bunch of comments on the page, and a lot of them talk about how the look feel and functionality should work, and I think it might be counter productive to bring each one into Github/Huboard as individual tasks.  The one task is to use the layout and functionality notes on that page as a guide, but make it look BETTER than it does in the mock up.

**Comment by ChrisASearles** [comment] 2017-05-10 13:48
This is a duplicate of #29

**Closed by ChrisASearles** 2017-05-10 13:48 UTC
Labels: 0 - Backlog
